# Generated by Django 2.2.7 on 2020-04-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='offline_counter',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('query1', models.IntegerField()),
                ('query2', models.IntegerField()),
                ('query3', models.IntegerField()),
                ('model', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
