# Generated by Django 2.2.7 on 2020-04-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offline_counter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
