# Generated by Django 2.2.7 on 2020-04-11 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200402_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='offline_confirmed',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('query1', models.IntegerField()),
                ('query2', models.IntegerField()),
                ('query3', models.IntegerField()),
                ('model', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
